### PR TITLE
Update 4D5307DF - Blue Dragon.patch.toml

### PR DESCRIPTION
**Pull request by Wyliemaster**
Debug Menu figured out on english releases. Credits to [Drago](https://github.com/megadrago88) for helping
image

Features of this debug menu are a bit unstable but the folks at the [blue dragon speedrunning discord server](https://discord.gg/gqpBMVh9xP) are working on stablising these features

### CODE REVIEW

**Comment by Wyliemaster** [comment]
Forgot some testing, will reopen when things are sorted

**Comment by Wyliemaster** [comment]
idk whats wrong with the lint, erroring on things i didn't change

image

**Comment by illusion0001** [comment]
> idk whats wrong with the lint, erroring on things i didn't change
> 
> image

Whitespaces

**Comment by illusion0001** [comment]
See the diff for context

**Pull request merged**
