### PR TITLE
Mod Patches

### PR DESCRIPTION
**Pull request by TeddyHammer**

### CODE REVIEW

**Comment by Gliniak** [comment]
Cleanup these commits please. It looks so bad right now

**Comment by TeddyHammer** [comment]
> Cleanup these commits please. It looks so bad right now

like what?

**Comment by Gliniak** [comment]
Like that. I would say. 
You still should have your branch locally and if you want to make such cleanup by yourself then I can teach you, so we can push it as you.

**Comment by TeddyHammer** [comment]
> Like that. I would say.
> You still should have your branch locally and if you want to make such cleanup by yourself then I can teach you, so we can push it as you.

i merged your clean up so we should be good

**Comment by illusion0001** [comment]
It's worse :thisisfine:

**Comment by TeddyHammer** [comment]
> It's worse :thisisfine:

wym

**Comment by Margen67** [comment]
> 
> 
> > It's worse :thisisfine:
> 
> wym

You didn't properly rebase:

**Pull request closed without merging**
