### PR TITLE
Patches for some games.

### PR DESCRIPTION
**Pull request by A1eNaz**
Mass Effect
Mass Effect 2
Medal of Honor
Grand Theft Auto V (TU10)
Grand Theft Auto V (TU18)
Minecraft (XBLA, TU75)

### CODE REVIEW

**Comment by Margen67** [comment]
These are supposed to go in the patches folder. Don't make a new pull request like last time, just fix this one.

**Comment by A1eNaz** [comment]
why does it say error for the media_id part?
image

**Comment by Margen67** [comment]
> why does it say error for the media_id part? image

I don't know. There's nothing wrong with it so I'll merge it once everything else is fixed.

**Comment by A1eNaz** [comment]
everything should be fine other than ME2 and MoH bugging out

**Pull request merged**
