### PR TITLE
Max Parts Infinite Ammo Fuel Cheats for B-K N&B

### PR DESCRIPTION
**Pull request by retrobenny**
(I had accidentally sent my own fork a pull request before this, hate when that happens...)

Max parts doesn't modify the actual owned parts count but it allows uncapped parts usage even after saving vehicles as long as the code is active. Want six Super Engines on a vehicle after getting one? No problem! (19 jets can be fun as well)

Ammo and Fuel Never Decrease cheat should be self-explanatory, allowing only needing smallest/lightest fuel and ammo for more broken vehicle building. Attempting to attach two ejector seat parts hangs the game, self destruct likely may also cause hanging with trying to add two or more.
Jets and Jets

### CODE REVIEW

**Comment by retrobenny** [comment]
Something else stupid happened... ...

**Comment by retrobenny** [comment]
I saw something before, mentioning my Breegull Bash wasn't matching the commit despite being merged.

Something outright stupid is going on with github or something.

I only want the single commit for the title, not the other two things, just the max parts commit.
Why is github being so damn stupid now?!?

**Comment by retrobenny** [comment]
image
Why is it doing 3 commits instead of my 1 commit that I want?

**Comment by retrobenny** [comment]
Can't figure out how to fix this, please help.

**Comment by retrobenny** [comment]
Sorry in advance for the pings, something went horribly wrong and I can't find any other solutions, out of options.

**Should I just delete my repository and create a fresh fork to attempt to fix this mess?** @illusion0001 @Margen67 

I only wanted the single commit in the pull request, not something that was already merged on the actual code which seems to have bugged out and it also includes my own synced to fork commit as an additional commit, adding to the worry.

All I wanted to do is add two codes to Banjo-Kazooie Nuts & Bolts but Github was having NONE of it.

**Comment by illusion0001** [comment]
You want to do rebase. `git rebase`

**Comment by retrobenny** [comment]
Still think something glitched out since the breegull bash commit, causing concern.

I use github in a browser, they really should've implemented easier access to that stuff on the browser version.
(the main thing being I don't have to use command-line stuff for stuff that has worked for me)

All my other previous stuff didn't destroy me like this one and the two total accidental PR creations into my own fork.
First time it happened was October 2021 when I added the Washing Machine Mach-6 fix for the Banjo-Tooie 60fps code.

**Comment by illusion0001** [comment]
It doesn't really matter, we always merge as squash or rebase and you can discard commits when merging from upstream

**Comment by retrobenny** [comment]
I have no idea what to do, could you fix my mess for me, please?
(part of it was caused by Github acting strange with some commits before, but still)

I don't know how to remove the "commits ahead" part from my fork so I can sync again in a proper way to clean up the muddled code results so nothing horrible ends up happening.

**Pull request closed without merging**
