### PR TITLE
Add a patch for enabling r_ugly_mode in Saints Row

### PR DESCRIPTION
**Pull request by Hasster1**
A hacky patch for enabling r_ugly_mode. Might be broken for someone. Needs some testing.

### CODE REVIEW

**Comment by Hasster1** [comment]
Requesting a verification....probably? I don't know how everything works around here, so excuse me if i'm being rude or too demanding.

**Comment by bomabomaboma** [comment]
No, you're good. 
I'll take a look at it tomorrow.
Thanks.

**Comment by BillieBlueberry** [comment]
_Why do we all have to have this ridiculous two-factor on?_

**Comment by Hasster1** [comment]
I've been mainly using canary_experimental@bf196ef64, because it has the keyboard_passthru, which is needed for the console, and it was a bit broken at the time, because i didn't know the difference between be8, be16 and be32, so it was working differently on the different canary versions. Now it's working properly on the old and new canary versions.

**Review by bomabomaboma — APPROVED** [review]

**Pull request merged**
