### PR TITLE
Random Tidbits: WET & TAA for Gears

### PR DESCRIPTION
**Pull request by bomabomaboma**

### CODE REVIEW

**Comment by bomabomaboma** [comment]
I'll add the 16x aniso patch for every UE game I own in the next couple days. Please keep the PR open for now.

**Comment by bomabomaboma** [comment]
I'm busy with personal stuff and honestly don't know when I'll have the time to add AF patches for a bunch of other games.
Ready for PR.
As always, I'll get back to adding more when I have free time.

**Review by bomabomaboma — COMMENTED** [review]
Changed original stw Gears AF patches to proper li r5,0x10 syntax

**Comment by illusion0001** [comment]
Commit hell part 2, let's hope it works

**Pull request merged**
